### ISSUE TITLE
Fix for ReDOS in REL1_35

### ISSUE THREAD

**Issue by osnard** [Universal-Omega/DynamicPageList3#75]
Sorry to ask again: So you do also actively maintain release branches?

If so, will there be a backport of the fix for https://github.com/Universal-Omega/DynamicPageList3/security/advisories/GHSA-8f24-q75c-jhf4 to `REL1_35`? As far as I could see, this issue was addressed by https://github.com/Universal-Omega/DynamicPageList3/commit/2c04dafb37a14d9ccfe070f53e7f11bbca0156e7. But this commit is not in `REL1_35`.

Or he otherway round: Will users of MediaWiki LTS 1.35 be able to patch the issue or are they advised to set `$wgDplSettings['functionalRichness'] = 0` as mentioned in the security advisory, because they can not use `3.3.6` ?

See also https://github.com/Universal-Omega/DynamicPageList3/issues/69

**Comment by Universal-Omega** [comment]
Thank you for your enquiry.

The fix is present on REL1_36 (I believe) and REL1_37, I am currently working on a new manual patch for REL1_35, due to conflicts it could not be backported.  As for the functional richness, yes that's is still possible. For the 1.35 fix I may just move the functional richness stuff around, allowing to only disable the regex stuff, as it is quite difficult to backport with all the recent changes to the codebase.

**Comment by osnard** [comment]
Understood. Thanks.

I didn't look into the big refactoring, so I can not tell what really requires MW Core 1.36. But maybe the easiest way would be to just take the current code (`3.6.7`) as a whole, put it to the `REL1_35`branch. Then adjust the compatibility constraint in `extension.json` and fix the incompatibilites. Such a backport may be simpler, as chances are good that there are only few differences between MW Core 1.35 and 1.36 that actually affect the extensions code.

**Comment by osnard** [comment]
Awesome! Thank you for merging! Could you please release 3.2.8, so people with MW 1.35 can properly update?

**Comment by Universal-Omega** [comment]
Now done https://github.com/Universal-Omega/DynamicPageList3/releases/tag/3.3.8
